

version: "3.1"

services:
  server:
  # папка с докерфайлом
    build: ./
    ports:
      - 8080:80
    environment:
      TEST_q: 'qweqwe'
      CACHE__REDIS__HOST : cacheservice
      CACHE__REDIS__PORT : 6379
      AppLogging__ElasticSearchUrl : http://elasticsearchservice
      AppLogging__ElasticSearchPort : 9200
      AppLogging__ElasticSearchLogin : elastic
      AppLogging__ElasticSearchPassword : MyPw123
      # Server=db - это обязательно название сервиса из compose файла - https://stackoverflow.com/questions/52926064/how-to-connect-to-sql-server-docker-container-from-another-container
      ConnectionStrings__DefaultConnection: 'Server=dbservice;Database=Menu-DataBase;User Id=SA;Password=SqlServerSuperPassword2017;Integrated Security=false;TrustServerCertificate=true'
      UseInMemoryDataProvider: 'false'
    depends_on:
      - cacheservice
      - dbservice
      - elasticsearchservice

  cacheservice:
  # dev variant
    image: redis/redis-stack:latest
    # image: redis/redis-stack-server - prod variant
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  dbservice:
    image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'SqlServerSuperPassword2017'
      ACCEPT_EULA: 'Y'
    volumes:
      # - mssql-server-linux-data:/var/opt/mssql/data
      - ./menu_volumes/menu-db-volume:/var/opt/mssql/data
      # - /data/project/mssql/log:/var/opt/mssql/log
      # - /data/project/mssql/secrets:/var/opt/mssql/secrets

  elasticsearchservice:
   container_name: elasticsearch
   image: elastic/elasticsearch:7.17.13 #docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - ./menu_volumes/elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    - xpack.security.enabled=true
    - "ELASTIC_USERNAME=elastic"
    - "ELASTIC_PASSWORD=MyPw123"
  #  networks:
  #   - elastic

  kibanaservice:
   container_name: kibana
   image: elastic/kibana:7.17.13 #docker.elastic.co/kibana/kibana:7.17.13
   ports:
    - 5601:5601
   depends_on:
    - elasticsearchservice
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - "ELASTICSEARCH_USERNAME=elastic"
    - "ELASTICSEARCH_PASSWORD=MyPw123"
  #  networks:
  #   - elastic
  
# networks:
#   elastic:
#     driver: bridge

# volumes:
#   mssql-server-linux-data:


