# version: '3.1'

# services:

#   elasticsearch:
#    container_name: elasticsearch
#    image: elastic/elasticsearch:7.17.13 #docker.elastic.co/elasticsearch/elasticsearch:7.9.2
#    ports:
#     - 9200:9200
#    volumes:
#     - ../menu_volumes/elasticsearch-data:/usr/share/elasticsearch/data
#    environment:
#     - xpack.monitoring.enabled=true
#     - xpack.watcher.enabled=false
#     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     - discovery.type=single-node
#     - xpack.security.enabled=true
#     - "ELASTIC_USERNAME=elastic"
#     - "ELASTIC_PASSWORD=MyPw123"
#    networks:
#     - elastic

#   kibana:
#    container_name: kibana
#    image: elastic/kibana:7.17.13 #docker.elastic.co/kibana/kibana:7.17.13
#    ports:
#     - 5601:5601
#    depends_on:
#     - elasticsearch
#    environment:
#     - ELASTICSEARCH_URL=http://localhost:9200
#     - "ELASTICSEARCH_USERNAME=elastic"
#     - "ELASTICSEARCH_PASSWORD=MyPw123"
#    networks:
#     - elastic
  
# networks:
#   elastic:
#     driver: bridge